server:
  port: 8016 #服务端口
eureka: #配置要eureka的信息
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
spring: #配置服务的名字
  application:
    name: education-Service-Web-Client
  servlet: #这个是你的服务需要上传文件的话才要配置的 
    multipart:
      max-file-size: 2000Mb      # Max file size，默认1M
      max-request-size: 2500Mb   # Max request size，默认10M
  jackson: #整个服务的日期都会被转换成这个格式,如果前端给了一个不是这个格式的日期,比如给了yyyy-MM-dd 格式的,那么就会报错
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf: #配置模板引擎
    prefix: classpath:/templates/
    servlet:
      content-type: text/html; charset=utf-8
    mode: HTML
    cache: false
    suffix: .html
  #mvc:
   # static-path-pattern: /static/**
    
management: #开启全部的监听端点
  endpoints:
    web:
      exposure:
        include: "*"
        
##################
 ###数据库配置
 ##################
 #database connection config
#mysql
---
spring: 
   datasource:
      url: jdbc:mysql://localhost:3306/ssh?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
# 指定的DBMS
   jpa:
      database: MYSQL

# 是否显示每个SQL查询的日志
      show-sql: true

# Hibernate ddl auto (create, create-drop, update)create 启动时删数据库中的表，然后创建，退出时不删除数据表 
#create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错 
#update 如果启动时表格式不一致则更新表，原有数据保留 
#validate 项目启动表结构进行校验 如果不一致则报错
      hibernate:
          ddl-auto: update
# Naming strategy(定义的数据库字段名的命名规则)
          naming:
                  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# stripped before adding them to the entity manager（在将它们添加到实体管理器之前删除）
      properties:
          hibernate:
             dialect: org.hibernate.dialect.MySQL5Dialect

